# Generated by Django 4.2.6 on 2023-10-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCT', models.CharField(max_length=50)),
                ('DESCRIPTION', models.TextField()),
                ('PRICE', models.IntegerField(default=0)),
                ('IMAGE', models.ImageField(upload_to='files/')),
            ],
        ),
    ]
