# Generated by Django 4.2.6 on 2024-01-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='PRODUCT',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='PRICE',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='QUANTITY',
        ),
        migrations.RemoveField(
            model_name='order',
            name='USER_ID',
        ),
    ]
