# Generated by Django 4.2.6 on 2024-01-27 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_orders_price_orders_quantity_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 27, 18, 3, 13, 85391)),
        ),
    ]
