# Generated by Django 4.2.6 on 2024-02-04 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_login',
            name='name',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 4, 17, 24, 34, 195462)),
        ),
    ]
