# Generated by Django 4.2.6 on 2024-02-04 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_admin_login_name_alter_orders_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_login',
            name='name',
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 4, 17, 28, 16, 785780)),
        ),
    ]
