# Generated by Django 4.2.6 on 2024-02-04 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_admin_login_name_alter_orders_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_login',
            name='names',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 4, 17, 30, 2, 291883)),
        ),
    ]
