# Generated by Django 4.2.6 on 2024-02-12 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_admin_login_names_alter_orders_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 12, 16, 47, 14, 540468)),
        ),
    ]
