# Generated by Django 4.2.6 on 2024-02-12 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_orders_date_alter_orders_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 12, 17, 11, 48, 607886)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
