# Generated by Django 4.2.6 on 2024-02-12 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_orders_date_alter_orders_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='id',
            new_name='ids',
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 12, 17, 13, 34, 230108)),
        ),
    ]
